steps:
  # Step 1: Conditionally build the base image
  - name: 'gcr.io/cloud-builders/docker'
    id: BuildBaseImage
    waitFor: ["-"]
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$_BUILD_BASE_IMAGE" == "true" ]; then
          docker build -t gcr.io/$PROJECT_ID/dbx-base -f Dockerfile.base .;
        else
          echo "Skipping base image build";
        fi

  # Step 2: Build the application image using the base image
  - name: 'gcr.io/cloud-builders/docker'
    id: BuildAppImage
    waitFor: ["BuildBaseImage"]
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed "s/{{PROJECT_ID}}/$PROJECT_ID/g" Dockerfile.app.tmpl > Dockerfile.app
        docker build -t gcr.io/$PROJECT_ID/dbx -f Dockerfile.app .

images:
  - 'gcr.io/$PROJECT_ID/dbx'
  - 'gcr.io/$PROJECT_ID/dbx-base'
