# Dockerfile.app.tmpl

# Stage 1: Build the Go application
FROM golang:1.22 as builder

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files and download the dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code into the container
COPY . .

# Build the Go application
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o /app/main .

# Stage 2: Create the final image
FROM gcr.io/{{PROJECT_ID}}/dbx-base

# Set the working directory inside the container
WORKDIR /app

# Copy the built Go application from the builder
COPY --from=builder /app/main /app/main

# Expose port 8080 for Cloud Run
EXPOSE 8080

# Run the Go application
CMD ["/app/main"]
