database:
  source:
    type: postgres
    user: postgres
    password: notapassword
    host: localhost
    port: 5432
    dbname: tfmv
  target:
    type: sqlite
    dbname: /Users/thomasmcgeehan/dbX/dbX/data/lite/chinook.db
local:
  base_dir: /Users/thomasmcgeehan/dbX/dbX/data
